version: '3'

services:
  ros:
    container_name: 'ros1'
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    entrypoint: sh -c 'echo "ROS is ready" && tail -f /dev/null'
    working_dir: /home/notroot/projects
    volumes:
      - ./ros_data:/home/notroot/.ros
      - ./projects:/home/notroot/projects

